### ISSUE TITLE
Pidgin 2.12.0 can't connect to the server

### ISSUE THREAD

**Issue by siohaza** [mk6i/retro-aim-server#14]
## Steps to reproduce issue:
1. Install [Pidgin 2.12.0](https://sourceforge.net/projects/pidgin/files/Pidgin/2.12.0/pidgin-2.12.0-offline.exe/download)
2. In `settings.env` enable auth by setting `DISABLE_AUTH` to false
3. Start server
4. `curl -d'{"screen_name":"asd123", "password":"asd123"}' http://localhost:8080/user`
5. Add account in Pidgin
6. In `Advanced` change server and port to `127.0.0.1:5190`
7. Set `Connection security` to `Don't use encryption`
8. Set `Authentication method` to `MD5-based`
9. Login in Pidgin
10. Pidgin reports `asd123 disconnected: Server closed the connection`

Sever logs are [here](https://privatebin.net/?ba7d0530e1f48976#CpHePe5B7zXavjTbbAEimBbrU1hJrMzDKdFZnb1oaif1)

**Comment by mk6i** [comment]
Thanks for the detailed report. Can you copy the log contents here? Looks like that paste is going to expire in 2 days.

**Comment by mk6i** [comment]
This is the error that causes disconnection:

```
time=2024-05-14T14:17:59.155+03:00 level=TRACE msg="client request" svc=BOS request.food_group=Locate request.sub_group=LocateSetInfo request.snac_frame="{FoodGroup:2 SubGroup:4 Flags:0 RequestID:15}" request.snac_payload="{TLVRestBlock:{TLVList:[{Tag:4 Value:[]}]}}" screenName=asd123 ip=127.0.0.1:55820
time=2024-05-14T14:17:59.155+03:00 level=ERROR msg="client request error" svc=BOS request.food_group=OService request.sub_group=OServiceSetUserInfoFields err="don't know what to do with status 268566528" screenName=asd123 ip=127.0.0.1:55820
```

It can be traced back to this block in the SetUserInfoFields [SNAC handler](https://github.com/mk6i/retro-aim-server/blob/2becefe1178c3322ec59f54174b709e54353098c/foodgroup/oservice.go#L420):

```go
if status, hasStatus := inBody.Uint32(wire.OServiceUserInfoStatus); hasStatus {
	switch status {
	case 0x0000:
		sess.SetInvisible(false)
		if err := broadcastArrival(ctx, sess, s.messageRelayer, s.feedbagManager, s.legacyBuddyListManager); err != nil {
			return wire.SNACMessage{}, err
		}
	case 0x0100:
		sess.SetInvisible(true)
		if err := broadcastDeparture(ctx, sess, s.messageRelayer, s.feedbagManager, s.legacyBuddyListManager); err != nil {
			return wire.SNACMessage{}, err
		}
	default:
		return wire.SNACMessage{}, fmt.Errorf("don't know what to do with status %d", status)
	}
}
```

The client receives a status value of `0x10020000`, but they only two supported values are `0x0000` and `0x0100`. The block should treat the `status` as a bitmask and check for the presence of flags rather than do a straight integer comparison.

I traced the origin of the flags set in `0x10020000` back to the [corresponding client code](https://keep.imfreedom.org/pidgin/pidgin/file/v2.12.0/libpurple/protocols/oscar/family_oservice.c#l812) in pidgin:

```c
if (seticqstatus)
{
	aim_tlvlist_add_32(&tlvlist, 0x0006, icqstatus |
			AIM_ICQ_STATE_HIDEIP | AIM_ICQ_STATE_DIRECTREQUIREAUTH);
}
```

Both flags `ORed` together equal `0x10020000` [(source)](https://keep.imfreedom.org/pidgin/pidgin/file/v2.12.0/libpurple/protocols/oscar/oscar.h#l424):

```c
#define AIM_ICQ_STATE_HIDEIP            0x00020000
//...
#define AIM_ICQ_STATE_DIRECTREQUIREAUTH 0x10000000
```

The set info handler should be able to process flags that it doesn't support without returning an error.

Here's how I would fix the bug:
1) Copy the [status constants](https://keep.imfreedom.org/pidgin/pidgin/file/v2.12.0/libpurple/protocols/oscar/oscar.h#l410) to [wire/snacs.go](https://github.com/mk6i/retro-aim-server/blob/2becefe1178c3322ec59f54174b709e54353098c/wire/snacs.go#L99).
2) Replace the above if statement with bitmask checks for each oservice status constant. Right now we only support visibile/invisible, but may support additional ones in the future. For unsupported constants, just log the presence of an unsupported constant and carry on.

```go
if status, hasStatus := inBody.Uint32(wire.OServiceUserInfoStatus); hasStatus {
	if status&wire.OServiceStatusVisible == wire.OServiceStatusVisible {
		sess.SetInvisible(false)
		if err := broadcastArrival(ctx, sess, s.messageRelayer, s.feedbagManager, s.legacyBuddyListManager); err != nil {
			return wire.SNACMessage{}, err
		}
	}
	if status&wire.OServiceStatusInvisible == wire.OServiceStatusInvisible {
		sess.SetInvisible(true)
		if err := broadcastDeparture(ctx, sess, s.messageRelayer, s.feedbagManager, s.legacyBuddyListManager); err != nil {
			return wire.SNACMessage{}, err
		}
	}
	if status&wire.OServiceStatusRequireDirectAuth == wire.OServiceStatusRequireDirectAuth {
		s.Infof("got unsupported status %d", status)
	}
	/// ...
}
```

I'm going to leave this issue open for newcomers. I think the fix is pretty simple, even for those without go experience.
