### ISSUE TITLE
Server behind a NAT

### ISSUE THREAD

**Issue by rhandorf** [mk6i/retro-aim-server#27]
Hi there,

I just want to say amazing project! I pulled it, installed and can run it on the local network without any problem. When I try and do port forwarding via NAT from a public IP to a private IP for the server, no one can log into the instance from the public IP despite the iptables rules getting counters increasing for the 5190-5194 TCP ports, and tcpdump showing traffic moving. I tried setting the host IP to being the public IP on NAT, the host's private IP in the NAT, and 0.0.0.0.

If I move the service to a public IP address, clients that are NAT'd are able to connect and talk just fine with the server on a public IP address.

I then tried using socat to do port looping, but ran into a problem there because despite telling the service to listen on a specific IP, it always goes to 0.0.0.0. I also tried setting the server to listen to 0.0.0.0, and then no one can connect to it.

What logs and test cases would you like to see so that I can hopefully have the server running behind a NAT vs being run on a host exposed to the Internet?

**Comment by mk6i** [comment]
Thanks for the feedback! Check out the networking issue described in https://github.com/mk6i/retro-aim-server/issues/29, which I think might be related to your issue. Do you think the solution detailed in that issue will solve the problem you're experiencing?

**Comment by jgknight** [comment]
I think there's a slight misunderstanding going on here, it could even be on my part trying to read through this. @rhandorf maybe you could clarify what the actual problem is, since you were able to get it working?

Right now as it stands, `OSCAR_HOST` is not telling the server what IP to listen on. That IP is what retro-aim-server is telling AIM clients to connect to after they've authenticated. #29 will help make some of this more clear, and maybe a little more flexible for situations where you want to use alternate port numbers.

So you can use NAT today - you just have to set `OSCAR_HOST` to the public IP address. I have this working fine in Docker on a cloud server where the server doesn't actually have a public IP assigned. 

However, @rhandorf if you're trying to do something like have both internal clients connect to the server's private IP and external clients connect server's public IP, using the same retro-aim-server instance, that's not going to work right now, because you can only configure a single `OSCAR_HOST` value.  You essentially need to treat it as if it's in a DMZ and always use the public IP, or it'd be a feature request to support multiple `OSCAR_HOST` values and how to handle selecting which one to use.

**Comment by rhandorf** [comment]
Thank ya for the info!

Hypothetically speaking from an IP address perspective, if I have the application running on a host who's IP is 192.168.1.100, and the external IP is 8.8.8.80, I have to configure OSCAR_HOST to being 8.8.8.80 and set all the DNS records to point to 8.8.8.80 and not be able to have internal hosts have a DNS record for 192.168.1.100?

Thanks for clarifying that last point; that's what I was trying to do in the example above. If not have multiple OSCAR_HOST values, maybe be able to have two separate retro-aim-server's connect to each other?

**Comment by rhandorf** [comment]
Setting OSCAR_HOST as the hostname opposed to the IP address seemed to work great!

**Comment by mk6i** [comment]
Excellent 👍
