### ISSUE TITLE
Bind OSCAR server and management API server to different network interfaces

### ISSUE THREAD

**Issue by CoherentLogic** [mk6i/retro-aim-server#29]
### Description of the feature
I'd like to see the ability to bind the OSCAR server to one network interface (i.e. a public IP) and the management server to another (i.e. an RFC1918 LAN IP).

### Use case
This would help with separation of concerns and enhance security, since the auth database probably shouldn't be accessible from the public Internet in many cases (especially for production/hardened deployment environments).

### Deployment environment

* retro-aim-server version: any

* Install method: Pre-built

* Clients used: None yet

* Other relevant details:

### Potential challenges

* Might potentially break backwards compatibility on upgrades, for existing users, depending on how configuration is handled.

### Additional information

I feel like it might make sense to use something like the `OSCAR_HOST` environment variable for this. Perhaps `MGMT_HOST` or similar?

For backwards compatibility, perhaps it should fall back to whatever `OSCAR_HOST` happens to be if the new config variable is undefined? Not sure.

**Comment by mk6i** [comment]
**Current Situation**

Retro AIM Server has 6 TCP services, each binding to `0.0.0.0` (all available interfaces) with its own port.

- API service (`8080`)
- Alert service (`5194`)
- Auth service (`5190`)
- BOS service (`5191`)
- ChatNav service (`5193`)
- Chat service (`5192)

When signing in to AIM, the client initially connects to port the Auth service, from which the receive a hostname that directs them to the BOS service. The BOS hostname is the concatenation of `OSCAR_HOST`:`BOS_PORT`. `OSCAR_HOST` is the hostname that must be addressable by the client.

Once connected to the BOS service, the client performs one or more service discovery requests for the hostnames of the remaining services, each of which has the same format. For example: `OSCAR_HOST`:`CHAT_PORT` for the Chat service,  `OSCAR_HOST`:`ALERT_PORT` for the Alert service, etc.

**Problem**

This setup poses two problems. 

1) It's not currently possible to override the default `0.0.0.0` binding.
2) Each service binds to the same port that is used by the hostname the client connects to. This couling makes it difficult to run the service with NAT, because with NAT the port the clients connect to may not be the same port the server binds to.

**Solution**

Here's how the new [Config](https://github.com/mk6i/retro-aim-server/blob/main/config/config.go) should look (feel free to adapt as necessary). Make sure to [regenerate the config files](https://github.com/mk6i/retro-aim-server/blob/main/docs/BUILD.md#config-file-generation).

We introduce two separate address configs: the bind address and the address the client connects to.

Note that the API host and Auth host are not "discoverable", so they won't have client hostname configurations.

```diff
diff --git a/config/config.go b/config/config.go
index 1faf490..8b40f74 100644
--- a/config/config.go
+++ b/config/config.go
@@ -3,15 +3,19 @@ package config
 //go:generate go run github.com/mk6i/retro-aim-server/cmd/config_generator windows settings.bat
 //go:generate go run github.com/mk6i/retro-aim-server/cmd/config_generator unix settings.env
 type Config struct {
-	ApiPort     string `envconfig:"API_PORT" required:"true" val:"8080" description:"The port that the management API service binds to."`
-	AlertPort   string `envconfig:"ALERT_PORT" required:"true" val:"5194" description:"The port that the Alert service binds to."`
-	AuthPort    string `envconfig:"AUTH_PORT" required:"true" val:"5190" description:"The port that the auth service binds to."`
-	BOSPort     string `envconfig:"BOS_PORT" required:"true" val:"5191" description:"The port that the BOS service binds to."`
-	ChatNavPort string `envconfig:"CHAT_NAV_PORT" required:"true" val:"5193" description:"The port that the chat nav service binds to."`
-	ChatPort    string `envconfig:"CHAT_PORT" required:"true" val:"5192" description:"The port that the chat service binds to."`
-	DBPath      string `envconfig:"DB_PATH" required:"true" val:"oscar.sqlite" description:"The path to the SQLite database file. The file and DB schema are auto-created if they doesn't exist."`
-	DisableAuth bool   `envconfig:"DISABLE_AUTH" required:"true" val:"true" description:"Disable password check and auto-create new users at login time. Useful for quickly creating new accounts during development without having to register new users via the management API."`
-	FailFast    bool   `envconfig:"FAIL_FAST" required:"true" val:"false" description:"Crash the server in case it encounters a client message type it doesn't recognize. This makes failures obvious for debugging purposes."`
-	LogLevel    string `envconfig:"LOG_LEVEL" required:"true" val:"info" description:"Set logging granularity. Possible values: 'trace', 'debug', 'info', 'warn', 'error'."`
-	OSCARHost   string `envconfig:"OSCAR_HOST" required:"true" val:"127.0.0.1" description:"The hostname that AIM clients connect to in order to reach OSCAR services (auth, BOS, BUCP, etc). Make sure the hostname is reachable by all clients. For local development, the default loopback address should work provided the server and AIM client(s) are running on the same machine. For LAN-only clients, a private IP address (e.g. 192.168..) or hostname should suffice. For clients connecting over the Internet, specify your public IP address and ensure that TCP ports 5190-5194 are open on your firewall."`
+	APIListenAddr     string `envconfig:"API_LISTEN_ADDR" required:"true" val:"0.0.0.0:8080" description:"The hostname and port that the management API service binds to."`
+	AlertClientAddr   string `envconfig:"ALERT_CLIENT_ADDR" required:"true" val:"127.0.0.1:5194" description:"The hostname and port that the client connects to for the Alert service."`
+	AlertListenAddr   string `envconfig:"ALERT_LISTEN_ADDR" required:"true" val:"0.0.0.0:5194" description:"The hostname and port that the Alert service binds to."`
+	AuthListenAddr    string `envconfig:"AUTH_LISTEN_ADDR" required:"true" val:"0.0.0.0:5190" description:"The hostname and port that the Auth service binds to."`
+	BOSClientAddr     string `envconfig:"BOS_CLIENT_ADDR" required:"true" val:"127.0.0.1:5191" description:"The hostname and port that the client connects to for the BOS service."`
+	BOSListenAddr     string `envconfig:"BOS_LISTEN_ADDR" required:"true" val:"0.0.0.0:5191" description:"The hostname and port that the BOS service binds to."`
+	ChatClientAddr    string `envconfig:"CHAT_CLIENT_ADDR" required:"true" val:"127.0.0.1:5192" description:"The hostname and port that the client connects to for the Chat service."`
+	ChatListenAddr    string `envconfig:"CHAT_LISTEN_ADDR" required:"true" val:"0.0.0.0:5192" description:"The hostname and port that the Chat service binds to."`
+	ChatNavClientAddr string `envconfig:"CHAT_NAV_CLIENT_ADDR" required:"true" val:"127.0.0.1:5193" description:"The hostname and port that the client connects to for the ChatNav service."`
+	ChatNavListenAddr string `envconfig:"CHAT_NAV_LISTEN_ADDR" required:"true" val:"0.0.0.0:5193" description:"The hostname and port that the Chat Nav service binds to."`
+	DBPath            string `envconfig:"DB_PATH" required:"true" val:"oscar.sqlite" description:"The path to the SQLite database file. The file and DB schema are auto-created if they doesn't exist."`
+	DisableAuth       bool   `envconfig:"DISABLE_AUTH" required:"true" val:"true" description:"Disable password check and auto-create new users at login time. Useful for quickly creating new accounts during development without having to register new users via the management API."`
+	FailFast          bool   `envconfig:"FAIL_FAST" required:"true" val:"false" description:"Crash the server in case it encounters a client message type it doesn't recognize. This makes failures obvious for debugging purposes."`
+	LogLevel          string `envconfig:"LOG_LEVEL" required:"true" val:"info" description:"Set logging granularity. Possible values: 'trace', 'debug', 'info', 'warn', 'error'."`
+	OSCARHost         string `envconfig:"OSCAR_HOST" required:"true" val:"127.0.0.1" description:"The hostname that AIM clients connect to in order to reach OSCAR services (auth, BOS, BUCP, etc). Make sure the hostname is reachable by all clients. For local development, the default loopback address should work provided the server and AIM client(s) are running on the same machine. For LAN-only clients, a private IP address (e.g. 192.168..) or hostname should suffice. For clients connecting over the Internet, specify your public IP address and ensure that TCP ports 5190-5194 are open on your firewall."`
 }
```

Next update the following calls to `net.Listen` to use the new `...ListenAddr` hostnames:

- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/server/oscar/alert.go#L32
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/server/oscar/auth.go#L38
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/server/oscar/bos.go#L37
- https://github.com/mk6i/retro-aim-server/blob/main/server/oscar/chat.go#L29
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/server/oscar/chat_nav.go#L31
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/server/http/mgmt_api.go#L57

Then update the service discovery handlers to use the new `...ClientAddr` hostnames:

- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/foodgroup/oservice.go#L533
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/foodgroup/oservice.go#L552
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/foodgroup/oservice.go#L588
- https://github.com/mk6i/retro-aim-server/blob/075be5eaad11d445392f9d51f3b25331d1ab68fe/foodgroup/auth.go#L254
